### ISSUE TITLE
Starlight Blog doesn't override MarkdownContent.astro since Starlight Image Zoom was added

### ISSUE THREAD

**Issue by trueberryless** [mscerts/hub#22]
Hello!

I think you have a unnoticed problem with your blog because if you look at the one blog post, you'll see that the author and creatingTime and all the features from Starlight Blog aren't rendering properly any more. This unintended behaviour is probably since https://github.com/mscerts/hub/commit/7cd6c6eddaedb834752127f7bb0d59c918b0c270 (addition of Starlight Image Zoom).

The reason for this problem is as following: Starlight Image Zoom AND Starlight Blog plugins both try to override the `MarkdownContent.astro` component from Starlight. This doesn't work because only ONE plugin can override a component. Hence, the Starlight Blog gives you a warning in the build process, that it can't override the `MarkdownContent.astro` component any more (but it doesn't through an error, so it builds successfully).

Unfortunately, I currently have no solution to this problem because I can't figure out how to override the component correctly.

Fortunately, I'm currently trying to figure out how to make both plugins work together by writing with the creator of both plugins: HiDeoo.

If I remember, I'll create a PR for you which should fix this issue when I have figured out how I can override it correctly.

In the meantime: You could comment the integration of Starlight Image Zoom:

```
integrations: [
		starlight({
			plugins: [
				//starlightImageZoom(),
				starlightBlog({
					authors: {
						nighthouse: {
						name: 'nighthouse',
```

**Comment by n1ghthouse** [comment]
Issue noted, merged the request that fixes the bug for the time being. Thank you ♥
